package dummyData;

public class MyDummyData {
	
	public static String testComplexJSONResponseString()
	{
		return "[\r\n"
				+ "  {\r\n"
				+ "    \"id\": 9001,\r\n"
				+ "    \"collection\": \"Tom Cruise Movies\",\r\n"
				+ "    \"favorite actor\": true,\r\n"
				+ "    \"List\": [\r\n"
				+ "      {\r\n"
				+ "        \"title\": \"Mission Impossible 1\",\r\n"
				+ "        \"year\": 1996,\r\n"
				+ "        \"cast roles\": [\r\n"
				+ "          \"Ethan Hunt\",\r\n"
				+ "          \"Luther\",\r\n"
				+ "          \"Jim\",\r\n"
				+ "          \"Max\",\r\n"
				+ "          \"Sarah\"\r\n"
				+ "        ],\r\n"
				+ "        \"director\": \"Brian De Palma\",\r\n"
				+ "        \"producer\": [\r\n"
				+ "          \"tom cruise\",\r\n"
				+ "          \"Paula Wagner\"\r\n"
				+ "        ],\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"runtime\": \"1 Hr 50 mins\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"title\": \"Mission Impossible 2\",\r\n"
				+ "        \"year\": 2000,\r\n"
				+ "        \"cast roles\": [\r\n"
				+ "          \"Ethan Hunt\",\r\n"
				+ "          \"Luther\",\r\n"
				+ "          \"Nyah\",\r\n"
				+ "          \"Sean\",\r\n"
				+ "          \"Wallis\"\r\n"
				+ "        ],\r\n"
				+ "        \"director\": \"John Woo\",\r\n"
				+ "        \"producer\": [\r\n"
				+ "          \"tom cruise\",\r\n"
				+ "          \"Paula Wagner\"\r\n"
				+ "        ],\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"runtime\": \"2 Hr 3 mins\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"title\": \"Mission Impossible 3\",\r\n"
				+ "        \"year\": 2006,\r\n"
				+ "        \"cast roles\": [\r\n"
				+ "          \"Ethan Hunt\",\r\n"
				+ "          \"Luther\",\r\n"
				+ "          \"Julia\",\r\n"
				+ "          \"Davian\",\r\n"
				+ "          \"Zhen\",\r\n"
				+ "          \"Benji\"\r\n"
				+ "        ],\r\n"
				+ "        \"director\": \"J J Abrams\",\r\n"
				+ "        \"producer\": [\r\n"
				+ "          \"tom cruise\",\r\n"
				+ "          \"Paula Wagner\",\r\n"
				+ "          \"Zhao Haicheng\"\r\n"
				+ "        ],\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"runtime\": \"2 Hr 6 mins\"\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "]";
		
	}
	

}
